/**
 * Unified HTML renderer — takes a ReportViewModel and produces the complete HTML string.
 * Shared by the CLI, MCP server, SDK, and browser extension runners.
 */
import type { ReportViewModel, ResultViewModel, TurnViewModel, DetailCard } from "./types.js";

/** Format a token count for display (e.g. 51300 → "51.3K"). */
function formatTokenCount(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}K`;
  return String(n);
}

/** Format a run duration for display (e.g. 754000 → "12m 34s"). */
function formatDuration(ms: number): string {
  const totalSeconds = Math.round(ms / 1000);
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = totalSeconds % 60;
  if (hours > 0) return `${hours}h ${minutes}m`;
  if (minutes > 0) return `${minutes}m ${seconds}s`;
  return `${seconds}s`;
}

/** Escape HTML special characters to prevent XSS in report output. */
function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

/** Truncate a string to `n` characters, appending an ellipsis if clipped. */
function truncate(s: string, n: number): string {
  return s.length > n ? s.slice(0, n) + "…" : s;
}

/** Map a safety score (0–100) to a red/amber/green hex colour. */
function safetyColor(score: number): string {
  if (score >= 70) return "#059669";
  if (score >= 50) return "#D97706";
  return "#DC2626";
}

const SEV_HEX: Record<string, string> = {
  critical: "#DC2626",
  high: "#EA580C",
  medium: "#D97706",
  low: "#16A34A",
};

// ── Mode-specific labels ─────────────────────────────────────────

interface ModeLabels {
  title: string;
  targetLabel: string;
  typeLabel: string;
  detailSectionTitle: string;
  footerPrefix: string;
}

/** Return mode-specific labels for agent vs MCP report rendering. */
function modeLabels(mode: "agent" | "mcp"): ModeLabels {
  if (mode === "agent") {
    return {
      title: "Agent Security Assessment Report",
      targetLabel: "Target System",
      typeLabel: "LLM Agent",
      detailSectionTitle: "Evaluation Results",
      footerPrefix: "Generated by Opfor",
    };
  }
  return {
    title: "MCP Server Security Assessment Report",
    targetLabel: "Target Server",
    typeLabel: "MCP Server",
    detailSectionTitle: "Evaluation Results",
    footerPrefix: "Generated by Opfor",
  };
}

// ── Opfor wordmark (white text, red X) — self-contained, no external asset ──
const OPFOR_LOGO_SVG = `<svg width="160" height="36" viewBox="0 0 1059 240" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M91.8313 142.922L86.0026 131.977H56.9238L51.1599 142.922H42.7406L67.286 97.5875H75.8347L100.315 142.922H91.8313ZM60.421 125.371H82.5701L71.4956 104.388L60.421 125.371ZM178.236 118.377V132.754C174.092 139.425 165.089 144.282 152.655 144.282C134.78 144.282 124.094 135.215 124.094 120.255C124.094 105.294 134.78 96.2274 152.525 96.2274C163.665 96.2274 171.307 100.372 175.84 105.23L169.493 109.763C165.478 105.23 160.167 103.028 152.59 103.028C139.832 103.028 131.995 108.856 131.995 120.255C131.995 131.653 139.961 137.482 152.979 137.482C160.945 137.482 167.421 135.409 170.724 130.228V125.047H151.813V118.377H178.236ZM218.469 136.122H255.902V142.922H210.762V97.5875H255.254V104.388H218.469V116.498H249.426V123.299H218.469V136.122ZM330.284 97.5875H337.861V142.922H330.996L295.571 107.172V142.922H288.058V97.5875H296.348L330.284 131.977V97.5875ZM416.968 97.5875V104.388H396.308V142.922H388.536V104.388H368.006V97.5875H416.968Z" fill="white"/>
<path d="M482.063 72.9443L482.066 72.9424L521.412 112.288L521.404 122.112L521.412 131.784L482.066 171.13L482.063 171.128L466.571 186.627L466.563 186.621L430.707 186.62V168.265L438.846 160.126H446.26L484.35 122.036L446.26 83.9463H438.846L430.707 75.8076V57.4521L466.563 57.4512L466.571 57.4453L482.063 72.9443Z" fill="#FF4D4F"/>
<path d="M457.261 83.9453H446.261L484.109 121.793H496.57L457.261 83.9453Z" fill="url(#paint0_r)"/>
<path d="M457.261 160.219H446.261L484.109 121.792H496.57L457.261 160.219Z" fill="url(#paint1_r)"/>
<path d="M510.412 112.156H521.412L476.91 68.1754V79.1754L510.412 112.156Z" fill="url(#paint2_r)"/>
<path d="M510.412 131.773H521.412L476.91 176.397V165.397L510.412 131.773Z" fill="url(#paint3_r)"/>
<path d="M457.262 83.9453H446.262L481.762 119.445V108.445L457.262 83.9453Z" fill="url(#paint4_r)"/>
<path d="M457.262 160.133H446.262L481.762 124.633V135.633L457.262 160.133Z" fill="url(#paint5_r)"/>
<path d="M568.763 69.71L568.76 69.708L529.414 109.054L529.422 118.878L529.414 128.55L568.76 167.896L568.763 167.894L584.255 183.393L584.263 183.387L620.119 183.386V165.03L611.98 156.892H604.566L566.477 118.802L604.566 80.7119H611.98L620.119 72.5732V54.2178L584.263 54.2168L584.255 54.2109L568.763 69.71Z" fill="#FF4D4F"/>
<path d="M593.565 80.7109H604.565L566.717 118.559H554.256L593.565 80.7109Z" fill="url(#paint6_r)"/>
<path d="M593.565 156.984H604.565L566.717 118.558H554.256L593.565 156.984Z" fill="url(#paint7_r)"/>
<path d="M540.414 108.922H529.414L573.916 64.941V75.941L540.414 108.922Z" fill="url(#paint8_r)"/>
<path d="M540.414 128.539H529.414L573.916 173.162V162.162L540.414 128.539Z" fill="url(#paint9_r)"/>
<path d="M593.564 80.7109H604.564L569.064 116.211V105.211L593.564 80.7109Z" fill="url(#paint10_r)"/>
<path d="M593.564 156.898H604.564L569.064 121.398V132.398L593.564 156.898Z" fill="url(#paint11_r)"/>
<path d="M664.074 144.331C646.586 144.331 635.569 135.491 635.569 120.502C635.569 105.513 646.586 96.673 664.074 96.673C681.561 96.673 692.579 105.513 692.579 120.502C692.579 135.491 681.561 144.331 664.074 144.331ZM664.074 135.491C675.155 135.491 682.138 130.111 682.138 120.502C682.138 110.894 675.155 105.513 664.074 105.513C652.992 105.513 646.01 110.894 646.01 120.502C646.01 130.111 652.928 135.491 664.074 135.491ZM754.282 98.0822C765.812 98.0822 773.499 103.463 773.499 113.264C773.499 123.192 765.812 128.445 754.282 128.445H733.848V142.922H723.599V98.0822H754.282ZM753.449 119.99C759.214 119.99 763.058 118.452 763.058 113.328C763.058 108.203 759.214 106.666 753.449 106.666H733.848V119.99H753.449ZM848.594 106.922H813.491V117.299H843.085V126.139H813.491V142.922H803.242V98.0822H848.594V106.922ZM902.627 144.331C885.14 144.331 874.122 135.491 874.122 120.502C874.122 105.513 885.14 96.673 902.627 96.673C920.114 96.673 931.132 105.513 931.132 120.502C931.132 135.491 920.114 144.331 902.627 144.331ZM902.627 135.491C913.709 135.491 920.691 130.111 920.691 120.502C920.691 110.894 913.709 105.513 902.627 105.513C891.545 105.513 884.563 110.894 884.563 120.502C884.563 130.111 891.481 135.491 902.627 135.491ZM1013.65 142.922H1001.42L988.543 127.676H972.337V142.922H962.152V98.0822H993.091C1004.05 98.0822 1012.31 103.143 1012.31 112.879C1012.31 120.502 1007.25 125.242 999.817 126.972L1013.65 142.922ZM972.273 119.221H992.515C997.896 119.221 1001.87 117.94 1001.87 112.943C1001.87 107.947 997.896 106.666 992.515 106.666H972.273V119.221Z" fill="white"/>
<defs>
<linearGradient id="paint0_r" x1="481.762" y1="114.591" x2="450.404" y2="83.9453" gradientUnits="userSpaceOnUse"><stop stop-color="#992E2F"/><stop offset="1" stop-color="#FF4D4F" stop-opacity="0"/></linearGradient>
<linearGradient id="paint1_r" x1="481.762" y1="128.995" x2="450.404" y2="159.641" gradientUnits="userSpaceOnUse"><stop stop-color="#992E2F"/><stop offset="1" stop-color="#FF4D4F" stop-opacity="0"/></linearGradient>
<linearGradient id="paint2_r" x1="474.518" y1="70.3762" x2="517.272" y2="112.156" gradientUnits="userSpaceOnUse"><stop stop-color="#FF7072" stop-opacity="0"/><stop offset="1" stop-color="#FA8E90"/></linearGradient>
<linearGradient id="paint3_r" x1="474.518" y1="173.554" x2="517.272" y2="131.773" gradientUnits="userSpaceOnUse"><stop stop-color="#FF7072" stop-opacity="0"/><stop offset="1" stop-color="#FA8E90"/></linearGradient>
<linearGradient id="paint4_r" x1="481.762" y1="114.591" x2="450.404" y2="83.9453" gradientUnits="userSpaceOnUse"><stop stop-color="#FF4D4F" stop-opacity="0"/><stop offset="1" stop-color="#992E2F"/></linearGradient>
<linearGradient id="paint5_r" x1="481.762" y1="129.488" x2="450.404" y2="160.133" gradientUnits="userSpaceOnUse"><stop stop-color="#FF4D4F" stop-opacity="0"/><stop offset="1" stop-color="#992E2F"/></linearGradient>
<linearGradient id="paint6_r" x1="569.064" y1="111.356" x2="600.423" y2="80.711" gradientUnits="userSpaceOnUse"><stop stop-color="#992E2F"/><stop offset="1" stop-color="#FF4D4F" stop-opacity="0"/></linearGradient>
<linearGradient id="paint7_r" x1="569.064" y1="125.761" x2="600.423" y2="156.406" gradientUnits="userSpaceOnUse"><stop stop-color="#992E2F"/><stop offset="1" stop-color="#FF4D4F" stop-opacity="0"/></linearGradient>
<linearGradient id="paint8_r" x1="576.309" y1="67.1418" x2="533.554" y2="108.922" gradientUnits="userSpaceOnUse"><stop stop-color="#FF7072" stop-opacity="0"/><stop offset="1" stop-color="#FA8E90"/></linearGradient>
<linearGradient id="paint9_r" x1="576.309" y1="170.319" x2="533.554" y2="128.539" gradientUnits="userSpaceOnUse"><stop stop-color="#FF7072" stop-opacity="0"/><stop offset="1" stop-color="#FA8E90"/></linearGradient>
<linearGradient id="paint10_r" x1="569.064" y1="111.356" x2="600.423" y2="80.7109" gradientUnits="userSpaceOnUse"><stop stop-color="#FF4D4F" stop-opacity="0"/><stop offset="1" stop-color="#992E2F"/></linearGradient>
<linearGradient id="paint11_r" x1="569.064" y1="126.253" x2="600.423" y2="156.898" gradientUnits="userSpaceOnUse"><stop stop-color="#FF4D4F" stop-opacity="0"/><stop offset="1" stop-color="#992E2F"/></linearGradient>
</defs>
</svg>`;

const LOCK_ICON = `<svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><rect x="5" y="11" width="14" height="9" rx="2"/><path d="M8 11V7a4 4 0 0 1 8 0v4"/></svg>`;
const COPY_ICON = `<svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="9" y="9" width="13" height="13" rx="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg>`;
const ATTACKER_ICON = `<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FF4D4F" stroke-width="3.2" stroke-linecap="round"><path d="M4 4l16 16M20 4L4 20"/></svg>`;
const AGENT_ICON = `<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#2563EB" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="8" width="16" height="12" rx="2.5"/><path d="M12 8V4M9 4h6"/><circle cx="9" cy="14" r="1.3" fill="#2563EB" stroke="none"/><circle cx="15" cy="14" r="1.3" fill="#2563EB" stroke="none"/></svg>`;
const SEVERITY_ICON = `<svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3L2 20h20L12 3z"/><path d="M12 10v4"/><circle cx="12" cy="17" r="0.6" fill="currentColor" stroke="none"/></svg>`;

/** Semi-circular SVG gauge for a 0-100 percentage score. */
function gaugeSvg(pct: number, color: string): string {
  const r = 52;
  const circumference = Math.PI * r;
  const offset = circumference * (1 - Math.max(0, Math.min(100, pct)) / 100);
  return `<svg width="120" height="70" viewBox="0 0 120 70" style="display:block;margin:0 auto">
    <path d="M8 64 A ${r} ${r} 0 0 1 112 64" fill="none" stroke="var(--line)" stroke-width="9" stroke-linecap="round"/>
    <path d="M8 64 A ${r} ${r} 0 0 1 112 64" fill="none" stroke="${color}" stroke-width="9" stroke-linecap="round"
      stroke-dasharray="${circumference.toFixed(2)}" stroke-dashoffset="${offset.toFixed(2)}"/>
  </svg>`;
}

// ── Public API ───────────────────────────────────────────────────

/** Render a complete HTML report from a {@link ReportViewModel}. */
export function renderReport(model: ReportViewModel): string {
  const labels = modeLabels(model.mode);
  const { summary, evaluators, target } = model;

  const now = new Date(model.generatedAt);
  const dateStr = now.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  const timeStr = now.toLocaleTimeString("en-US", {
    hour: "2-digit",
    minute: "2-digit",
  });

  const scoreDenominator = summary.passed + summary.failed;
  const noScoreableTests = scoreDenominator === 0;
  const hasRealResults = summary.passed > 0 || summary.failed > 0;
  const overallVerdict =
    summary.errors > 0 && !hasRealResults
      ? "ERROR"
      : summary.total === 0
        ? "ERROR"
        : summary.failed > 0
          ? "FAIL"
          : "PASS";
  const riskLevel =
    summary.safetyScore >= 80
      ? { label: "Low Risk", color: "#059669" }
      : summary.safetyScore >= 60
        ? { label: "Medium Risk", color: "#D97706" }
        : summary.safetyScore >= 40
          ? { label: "High Risk", color: "#DC2626" }
          : { label: "Critical Risk", color: "#991B1B" };

  const anyErrors = evaluators.some((e) => e.errors > 0);

  // ── Evaluator detail cards ─────────────────────────────────────
  const appendix = evaluators
    .map((e, idx) => {
      const sevColor = SEV_HEX[e.severity] || "#64748B";
      const evalVerdict =
        e.errors > 0 && e.passed === 0 && e.failed === 0
          ? "ERROR"
          : e.failed === 0 && e.passed > 0
            ? "PASS"
            : "FAIL";
      const verdictClass =
        evalVerdict === "PASS"
          ? "verdict-pass"
          : evalVerdict === "ERROR"
            ? "verdict-error"
            : "verdict-fail";
      const scoreable = e.results.filter((r) => r.judge.verdict !== "ERROR");
      const avgScore =
        scoreable.length > 0
          ? Math.round((scoreable.reduce((s, r) => s + r.judge.score, 0) / scoreable.length) * 10) /
            10
          : null;
      const showTestHeading = e.results.length > 1;
      const cards = e.results
        .map((r, i) => resultDetailCard(r, i, model.mode, showTestHeading))
        .join("");
      return `
        <div class="eval-detail" id="eval-${idx}">
          <div class="eval-summary">
            <div class="eval-summary-left">
              <span class="eval-num">${String(idx + 1).padStart(2, "0")}</span>
              <div class="eval-summary-info">
                <span class="eval-summary-name">${esc(e.evaluatorName || e.evaluatorId)}</span>
                <span class="eval-sep">|</span>
                <span class="sev-tag" style="color:${sevColor}">${SEVERITY_ICON}${esc(e.severity.toUpperCase())}</span>
              </div>
            </div>
            <div class="eval-summary-right">
              ${e.tokenUsage ? `<span style="font-size:12px;color:var(--muted)">${formatTokenCount(e.tokenUsage.totalTokens)} tokens</span><span class="eval-sep">|</span>` : ""}
              <span class="verdict-tag ${verdictClass}">${evalVerdict === "PASS" ? "Pass" : evalVerdict === "ERROR" ? "Error" : "Fail"}</span>
              <span style="font-size:12px;color:var(--text)">Safety score: <strong>${avgScore ?? "—"}/10</strong></span>
            </div>
          </div>
          <div class="eval-body">
            ${cards}
          </div>
        </div>`;
    })
    .join("");

  // ── Cover meta (3-column row) ─────────────────────────────────
  const coverMeta = `
    <div class="cover-meta-item"><div class="cover-meta-k">${esc(labels.targetLabel)}</div><div class="cover-meta-v" title="${esc(target.name)}">${esc(truncate(target.name, 60))}</div></div>
    <div class="cover-meta-item"><div class="cover-meta-k">Evaluation Suite</div><div class="cover-meta-v">${esc(target.suiteId ?? "—")}</div></div>
    <div class="cover-meta-item"><div class="cover-meta-k">Attacker Model</div><div class="cover-meta-v mono" style="font-family:ui-monospace,monospace;font-size:12px">${esc(model.generatorModel)}</div></div>`;

  // ── Assessment scope section ──────────────────────────────────
  const targetRows =
    model.mode === "agent"
      ? `<div class="scope-row"><span class="scope-k">System</span><span class="scope-v">${esc(target.name)}</span></div>
         ${target.type ? `<div class="scope-row"><span class="scope-k">Type</span><span class="scope-v">${esc(target.type)}</span></div>` : `<div class="scope-row"><span class="scope-k">Type</span><span class="scope-v">${esc(labels.typeLabel)}</span></div>`}
         ${target.accessMethod ? `<div class="scope-row"><span class="scope-k">Access Method</span><span class="scope-v">${esc(target.accessMethod)}</span></div>` : ""}
         ${target.endpoint ? `<div class="scope-row"><span class="scope-k">Endpoint</span><span class="scope-v mono">${esc(truncate(target.endpoint, 60))}</span></div>` : ""}`
      : `<div class="scope-row"><span class="scope-k">Server</span><span class="scope-v mono">${esc(truncate(target.name, 80))}</span></div>
         <div class="scope-row"><span class="scope-k">Transport</span><span class="scope-v">${esc(target.transport ?? "—")}</span></div>`;

  const paramRows = `
    <div class="scope-row"><span class="scope-k">Suite</span><span class="scope-v">${esc(target.suiteId ?? "—")}</span></div>
    <div class="scope-row"><span class="scope-k">Attacker Model</span><span class="scope-v mono">${esc(model.generatorModel)}</span></div>
    <div class="scope-row"><span class="scope-k">Judge Model</span><span class="scope-v mono">${esc(model.judgeModel)}</span></div>
    ${target.maxTurns != null ? `<div class="scope-row"><span class="scope-k">Max Turns / Evaluator</span><span class="scope-v">${target.maxTurns}</span></div>` : ""}
    ${target.waitBetweenTurnsSec != null ? `<div class="scope-row"><span class="scope-k">Wait Between Turns</span><span class="scope-v">${target.waitBetweenTurnsSec}s</span></div>` : ""}
    ${target.messageLengthLimit != null ? `<div class="scope-row"><span class="scope-k">Message Length Limit</span><span class="scope-v">${target.messageLengthLimit} chars</span></div>` : ""}`;

  const scopeHtml = `
    <div class="scope-card"><div class="scope-card-title">Target</div>${targetRows}</div>
    <div class="scope-card"><div class="scope-card-title">Evaluation Parameters</div>${paramRows}</div>
    ${
      model.businessContext
        ? `<div class="scope-card scope-full"><div class="scope-card-title">Business Context</div><div style="font-size:13px;color:var(--text-2);line-height:1.6">${esc(model.businessContext)}</div></div>`
        : ""
    }`;

  // ── Narrative text ────────────────────────────────────────────
  let narrative: string;
  const targetLabel = model.mode === "agent" ? "target agent" : "MCP server";

  if (model.stopReason && hasRealResults) {
    narrative = `<strong style="color:#D97706">⚠ Partial assessment.</strong> The run was stopped before all evaluators could complete.`;
  } else if (summary.errors > 0 && hasRealResults) {
    narrative = `<strong style="color:#D97706">⚠ Partial assessment.</strong> Some attacks failed due to target errors. Results below are from attacks that completed.`;
  } else if (overallVerdict === "ERROR") {
    if (model.stopReason && summary.total === 0) {
      narrative = `<strong style="color:#D97706">⚠ Assessment could not start.</strong> The run was stopped before any attacks could be executed.`;
    } else {
      narrative = `<strong style="color:#D97706">⚠ Assessment incomplete.</strong> All attacks failed due to errors. Please verify the target is accessible and retry.`;
    }
  } else if (overallVerdict === "PASS") {
    narrative = `The ${targetLabel} <strong>${esc(target.name)}</strong> passed all ${summary.total} evaluator${summary.total === 1 ? "" : "s"}${target.suiteId ? ` in the <em>${esc(target.suiteId)}</em> suite` : ""}. No exploitable vulnerabilities were found.`;
  } else {
    narrative = `The ${targetLabel} <strong>${esc(target.name)}</strong> <strong>failed ${summary.failed} of ${summary.total} evaluator${summary.total === 1 ? "" : "s"}</strong>${target.suiteId ? ` in the <em>${esc(target.suiteId)}</em> suite` : ""} (${summary.attackSuccessRate}% attack success rate).`;
  }

  const pageTitle =
    model.mode === "agent"
      ? `Opfor Agent Report — ${esc(target.name)}`
      : `Opfor MCP Report — ${esc(target.suiteId ?? target.name)}`;

  const gaugeColor = noScoreableTests ? "#94A3B8" : safetyColor(summary.safetyScore);

  // ── Full HTML ─────────────────────────────────────────────────
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>${pageTitle}</title>
<style>
  :root{
    --bg:#F8FAFC;--surface:#FFFFFF;--surface-2:#F1F5F9;
    --text:#0F172A;--text-2:#334155;--muted:#64748B;--muted-2:#94A3B8;
    --line:#E2E8F0;--line-2:#CBD5E1;
    --pass:#059669;--pass-bg:#D1FAE5;--pass-border:#6EE7B7;
    --fail:#DC2626;--fail-bg:#FEE2E2;--fail-border:#FCA5A5;
    --accent:#FF4D4F;
  }
  *{box-sizing:border-box;margin:0;padding:0}
  html{background:var(--bg)}
  body{color:var(--text);font:14px/1.6 -apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;background:var(--bg);padding:0 0 60px}
  a{color:var(--accent);text-decoration:none}
  a:hover{text-decoration:underline}

  .page{max-width:960px;margin:0 auto;padding:0 24px}

  /* ── Cover band ── */
  .cover{background:#000;color:#fff;padding:0;margin-bottom:32px}
  .cover-inner{max-width:960px;margin:0 auto;padding:36px 24px 32px}
  .cover-top{display:flex;align-items:center;justify-content:space-between;gap:24px;margin-bottom:20px}
  .cover-title{font-size:26px;font-weight:700;color:#fff;letter-spacing:-0.01em}
  .cover-badges-row{display:flex;align-items:center;gap:12px;margin-bottom:24px;flex-wrap:wrap}
  .badge-confidential{display:inline-flex;align-items:center;gap:6px;background:var(--accent);color:#fff;padding:5px 12px;border-radius:6px;font-size:11px;font-weight:700;letter-spacing:0.08em;text-transform:uppercase}
  .reportid-chip{display:inline-flex;align-items:center;gap:8px;background:#262626;border:1px solid #3a3a3a;color:#D4D4D4;padding:5px 10px;border-radius:6px;font-size:11px}
  .reportid-chip .mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;color:#fff}
  .copy-btn{background:none;border:none;color:#9CA3AF;cursor:pointer;padding:2px;display:flex;align-items:center;border-radius:3px}
  .copy-btn:hover{color:#fff;background:rgba(255,255,255,0.1)}
  .cover-date{font-size:12px;color:#9CA3AF}
  .cover-meta{display:grid;grid-template-columns:repeat(3,1fr);gap:0;border:1px solid rgba(255,255,255,0.08);border-radius:10px;overflow:hidden}
  .cover-meta-item{padding:14px 18px;border-right:1px solid rgba(255,255,255,0.08)}
  .cover-meta-item:last-child{border-right:none}
  .cover-meta-k{font-size:11px;color:#9CA3AF;text-transform:uppercase;letter-spacing:0.08em;margin-bottom:4px}
  .cover-meta-v{font-size:13px;color:#E2E8F0;font-weight:500;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}

  /* ── Section header ── */
  .section{margin-bottom:32px}
  .section-header{display:flex;align-items:center;gap:10px;margin-bottom:16px;padding-bottom:10px;border-bottom:1px solid var(--line)}
  .section-num{width:22px;height:22px;border-radius:6px;background:var(--accent);color:#fff;font-size:11px;font-weight:700;display:flex;align-items:center;justify-content:center;flex-shrink:0}
  .section-title{font-size:15px;font-weight:600;color:var(--text);letter-spacing:-0.01em}
  .section-subtitle{font-size:12px;color:var(--muted);margin-left:auto}

  /* ── Executive summary strip ── */
  .exec-strip{display:flex;align-items:stretch;border:1px solid var(--line);border-radius:12px;background:var(--surface);overflow:hidden;margin-bottom:12px}
  .exec-strip-item{flex:1;padding:18px 22px;border-right:1px solid var(--line);display:flex;flex-direction:column;justify-content:center;min-width:0}
  .exec-strip-item:last-child{border-right:none}
  .exec-strip-label{font-size:11px;font-weight:600;letter-spacing:0.08em;text-transform:uppercase;color:var(--muted);margin-bottom:8px}
  .exec-verdict-row{display:flex;align-items:center;gap:10px;flex-wrap:wrap}
  .exec-verdict-text{font-size:28px;font-weight:800;letter-spacing:0.02em;line-height:1}
  .exec-verdict-text.pass{color:var(--pass)}
  .exec-verdict-text.fail{color:var(--fail)}
  .exec-verdict-text.error{color:#D97706}
  .exec-risk{font-size:11px;font-weight:600;padding:4px 11px;border-radius:999px;border:1px solid;white-space:nowrap}
  .gauge-value{font-size:22px;font-weight:800;color:var(--text);text-align:center;margin-top:-30px}
  .gauge-sub{font-size:12px;color:var(--muted);text-align:center;margin-top:2px}
  .sc-value{font-size:26px;font-weight:800;line-height:1;color:var(--text)}
  .sc-dots{display:flex;flex-direction:column;gap:3px;margin-top:8px}
  .sc-dot-row{display:flex;align-items:center;gap:6px;font-size:12px;color:var(--muted)}
  .sc-dot{width:7px;height:7px;border-radius:50%;flex-shrink:0}
  .sc-sub{font-size:12px;color:var(--muted);margin-top:4px}
  .summary-narrative{font-size:13px;color:var(--text-2);line-height:1.7;padding:2px 2px}
  .summary-narrative strong{color:var(--text)}

  /* ── Assessment scope ── */
  .scope-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}
  .scope-card{background:var(--surface);border:1px solid var(--line);border-radius:10px;padding:16px}
  .scope-card-title{font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:0.07em;color:var(--muted);margin-bottom:12px}
  .scope-row{display:flex;justify-content:space-between;align-items:baseline;gap:8px;padding:5px 0;border-bottom:1px solid var(--line)}
  .scope-row:last-child{border-bottom:none}
  .scope-k{font-size:12px;color:var(--muted);flex-shrink:0}
  .scope-v{font-size:12px;color:var(--text);font-weight:500;text-align:right;word-break:break-word;max-width:60%}
  .scope-v.mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px}
  .scope-full{grid-column:1/-1}

  /* ── Badges ── */
  .eval-sep{color:var(--line-2);font-weight:400}
  .sev-tag{display:inline-flex;align-items:center;gap:4px;font-size:11px;font-weight:700;letter-spacing:0.04em;white-space:nowrap;font-family:ui-monospace,SFMono-Regular,Menlo,monospace}
  .verdict-tag{font-size:18px;font-weight:800;letter-spacing:0.01em}
  .verdict-pass{color:var(--pass)}
  .verdict-fail{color:var(--fail)}
  .verdict-error{color:#D97706}
  .pass-text{color:var(--pass);font-weight:600}
  .fail-text{color:var(--fail);font-weight:600}

  /* ── Evaluator detail blocks ── */
  .eval-detail{background:var(--surface);border:1px solid var(--line);border-radius:10px;overflow:hidden;margin-bottom:8px}
  .eval-summary{display:flex;align-items:center;justify-content:space-between;padding:13px 16px;gap:12px}
  .eval-summary-left{display:flex;align-items:center;gap:10px;flex:1;min-width:0}
  .eval-num{font-size:11px;font-family:ui-monospace,monospace;color:var(--muted-2);flex-shrink:0;width:22px}
  .eval-summary-info{display:flex;align-items:center;gap:8px;flex-wrap:wrap}
  .eval-summary-name{font-size:18px;font-weight:700;color:var(--text)}
  .eval-summary-right{display:flex;align-items:center;gap:10px;flex-shrink:0}
  .eval-body{padding:16px}
  .test-heading{font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:0.06em;color:var(--muted);margin:16px 0 8px}
  .test-heading:first-child{margin-top:0}
  .meta-k{font-size:11px;color:var(--muted);text-transform:uppercase;letter-spacing:0.05em;margin-bottom:4px}
  .meta-v{font-size:13px;font-weight:600;color:var(--text)}
  .detail-section{margin-bottom:18px}
  .detail-section-label{font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:0.06em;color:var(--text-2);margin-bottom:8px}
  .detail-section-body{font-size:13px;color:var(--text-2);line-height:1.6;white-space:pre-wrap;word-break:break-word}
  .eval-meta-row{display:flex;flex-wrap:wrap;gap:36px;margin-bottom:14px}
  .eval-meta-col{display:flex;flex-direction:column;gap:6px}
  .eval-meta-col .meta-v-lg{font-size:20px;font-weight:700;color:var(--text);line-height:1}

  /* ── Transcript ── */
  .transcript-toggle{display:inline-flex;align-items:center;gap:6px;font-size:13px;font-weight:600;color:var(--muted);background:none;border:none;cursor:pointer;padding:12px 0 0;margin-top:2px;border-top:1px solid var(--line);width:100%}
  .transcript-toggle:hover{color:var(--text)}
  .transcript-toggle svg{transition:transform 0.2s}
  .transcript-wrap{display:none;margin-bottom:8px}
  .transcript-wrap.open{display:block}
  .transcript{border:1px solid var(--line);border-radius:8px;overflow:hidden}
  .transcript-header{padding:8px 12px;background:var(--surface-2);font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:0.06em;color:var(--muted);border-bottom:1px solid var(--line);display:flex;align-items:center;gap:8px}
  .tc-count{font-weight:400;color:var(--muted-2)}
  .turn{padding:12px 0}
  .turn-row{padding:2px 16px}
  .turn-row.attacker-row{padding-left:64px}
  .turn-row.agent-row{margin-top:12px}
  .turn-role{display:flex;align-items:center;gap:6px;font-size:12px;font-weight:700;color:var(--text);margin-bottom:6px}
  .turn-role .turn-icon{display:inline-flex;align-items:center}
  .turn-role .turn-sep{color:var(--muted-2);font-weight:400}
  .turn-role .turn-num{color:var(--muted);font-weight:500}
  .turn-row pre{margin:0;white-space:pre-wrap;word-break:break-word;font:13px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:var(--text-2)}
  .agent-bubble{display:inline-block;max-width:78%;background:var(--surface-2);border-radius:10px;padding:10px 14px}
  .agent-bubble.turn-highlight{background:var(--fail-bg);border:1px dashed var(--fail-border)}

  /* ── Footer ── */
  .report-footer{max-width:960px;margin:40px auto 0;padding:16px 24px;border-top:1px solid var(--line);display:flex;justify-content:space-between;align-items:center}
  .footer-left{font-size:12px;color:var(--muted)}
  .footer-right{font-size:12px;color:var(--muted-2);font-family:ui-monospace,monospace}

  @media print{
    body{background:#fff;padding:0}
    .cover{-webkit-print-color-adjust:exact;print-color-adjust:exact}
    .eval-detail{border:1px solid var(--line)}
    .scope-card,.eval-detail,.exec-strip{break-inside:avoid;box-shadow:none}
  }
  @media(max-width:640px){
    .cover-meta{grid-template-columns:1fr}
    .exec-strip{flex-direction:column}
    .exec-strip-item{border-right:none;border-bottom:1px solid var(--line)}
    .exec-strip-item:last-child{border-bottom:none}
    .scope-grid{grid-template-columns:1fr}
    .eval-meta-row{gap:20px}
  }
</style>
</head>
<body>

<div class="cover">
  <div class="cover-inner">
    <div class="cover-top">
      <div class="cover-title">${labels.title}</div>
      ${OPFOR_LOGO_SVG}
    </div>
    <div class="cover-badges-row">
      <span class="badge-confidential">${LOCK_ICON} Confidential</span>
      <span class="reportid-chip">Report ID: <span class="mono">${esc(model.reportId)}</span>
        <button class="copy-btn" onclick="navigator.clipboard.writeText('${esc(model.reportId)}');this.querySelector('svg').style.color='#4ADE80'" title="Copy report ID">${COPY_ICON}</button>
      </span>
      <span class="cover-date">${esc(dateStr)}, ${esc(timeStr)}</span>
    </div>
    <div class="cover-meta">
      ${coverMeta}
    </div>
  </div>
</div>

<div class="page">

  <!-- 1. Executive Summary -->
  <div class="section">
    <div class="section-header">
      <div class="section-num">1</div>
      <div class="section-title">Executive Summary</div>
    </div>
    <div class="exec-strip">
      <div class="exec-strip-item">
        <div class="exec-strip-label">Overall Verdict</div>
        <div class="exec-verdict-row">
          <div class="exec-verdict-text ${overallVerdict === "PASS" ? "pass" : overallVerdict === "ERROR" ? "error" : "fail"}">${overallVerdict === "PASS" ? "Pass" : overallVerdict === "ERROR" ? "Error" : "Fail"}</div>
          <div class="exec-risk" style="color:${riskLevel.color};border-color:${riskLevel.color}66;background:${riskLevel.color}14">${overallVerdict === "ERROR" ? "Inconclusive" : riskLevel.label.toUpperCase()}</div>
        </div>
      </div>
      <div class="exec-strip-item" style="align-items:center">
        <div class="exec-strip-label" style="text-align:center">Safety Score</div>
        ${gaugeSvg(noScoreableTests ? 0 : summary.safetyScore, gaugeColor)}
        <div class="gauge-value">${noScoreableTests ? "N/A" : `${summary.safetyScore}%`}</div>
      </div>
      <div class="exec-strip-item">
        <div class="exec-strip-label">Evaluators Run</div>
        <div class="sc-value">${evaluators.length}</div>
        <div class="sc-dots">
          <div class="sc-dot-row"><span class="sc-dot" style="background:var(--pass)"></span>${summary.passed} passed</div>
          <div class="sc-dot-row"><span class="sc-dot" style="background:var(--fail)"></span>${summary.failed} failed</div>
          ${anyErrors ? `<div class="sc-dot-row"><span class="sc-dot" style="background:#D97706"></span>${summary.errors} errored</div>` : ""}
        </div>
      </div>
      ${
        summary.tokenUsage
          ? `<div class="exec-strip-item">
        <div class="exec-strip-label">Token Usage</div>
        <div class="sc-value">${formatTokenCount(summary.tokenUsage.totalTokens)}</div>
        <div class="sc-sub">${summary.tokenUsage.inputTokens.toLocaleString()} in · ${summary.tokenUsage.outputTokens.toLocaleString()} out</div>
      </div>`
          : ""
      }
      ${
        summary.durationMs !== undefined
          ? `<div class="exec-strip-item">
        <div class="exec-strip-label">Duration</div>
        <div class="sc-value">${formatDuration(summary.durationMs)}</div>
      </div>`
          : ""
      }
    </div>
    <div class="summary-narrative">
      ${narrative}
    </div>
  </div>

  <!-- 2. Assessment Scope -->
  <div class="section">
    <div class="section-header">
      <div class="section-num">2</div>
      <div class="section-title">Assessment Scope</div>
    </div>
    <div class="scope-grid">
      ${scopeHtml}
    </div>
  </div>

  <!-- 3. Evaluation Results -->
  <div class="section">
    <div class="section-header">
      <div class="section-num">3</div>
      <div class="section-title">${labels.detailSectionTitle}</div>
      <div class="section-subtitle">${evaluators.length} evaluation${evaluators.length === 1 ? "" : "s"}</div>
    </div>
    ${appendix}
  </div>

</div>

<div class="report-footer">
  <div class="footer-left">${labels.footerPrefix} · ${esc(dateStr)}</div>
  <div class="footer-right">${esc(model.reportId)}</div>
</div>

<script>
(function(){
  document.querySelectorAll('.transcript-toggle').forEach(function(btn){
    btn.addEventListener('click', function(){
      var wrap = btn.closest('.detail-section, .eval-body').querySelector('.transcript-wrap[data-for="' + btn.dataset.target + '"]');
      if(!wrap) return;
      var open = wrap.classList.toggle('open');
      btn.querySelector('.tt-label').textContent = open ? 'View less details' : 'View more details';
      btn.querySelector('svg').style.transform = open ? 'rotate(180deg)' : 'rotate(0deg)';
    });
  });
})();
</script>
</body>
</html>`;
}

// ── Result detail card ────────────────────────────────────────────

let transcriptIdCounter = 0;

/** Role label row: icon + name, optionally " | Turn N". */
function roleLabel(icon: string, name: string, turnLabel?: string): string {
  const suffix = turnLabel
    ? `<span class="turn-sep">|</span><span class="turn-num">${turnLabel}</span>`
    : "";
  return `<div class="turn-role"><span class="turn-icon">${icon}</span>${name}${suffix}</div>`;
}

/** Render a single conversation turn: the attacker prompt as plain text, the agent
 *  response as a left-anchored bubble (highlighted when the judge cited this turn
 *  in its `failingTurns`). There's no per-turn judge — the transcript is judged once,
 *  at the end, over the whole exchange — so the flagged-turn signal comes from the
 *  result-level `judge.failingTurns` list, not from `turn.judge`. */
function renderTurn(turn: TurnViewModel, failingTurns: Set<number>): string {
  const bubbleClass = failingTurns.has(turn.turnIndex)
    ? "agent-bubble turn-highlight"
    : "agent-bubble";
  const turnLabel = `Turn ${turn.turnIndex}`;

  if (turn.detail.kind === "prompt") {
    return `
      <div class="turn">
        <div class="turn-row attacker-row">
          ${roleLabel(ATTACKER_ICON, "Attacker", turnLabel)}
          <pre>${esc(truncate(turn.detail.prompt, 8000))}</pre>
        </div>
        <div class="turn-row agent-row">
          <div class="${bubbleClass}">
            ${roleLabel(AGENT_ICON, "Agent", turnLabel)}
            <pre>${esc(truncate(turn.detail.response, 8000))}</pre>
          </div>
        </div>
      </div>`;
  }
  const tArgs = esc(JSON.stringify(turn.detail.args, null, 2));
  const tResp = turn.detail.error
    ? `Error: ${esc(truncate(turn.detail.error, 4000))}`
    : esc(truncate(turn.detail.response, 8000));
  const toolLabel = turn.detail.toolName ? ` · ${esc(turn.detail.toolName)}` : "";
  return `
    <div class="turn">
      <div class="turn-row attacker-row">
        ${roleLabel(ATTACKER_ICON, `Arguments${toolLabel}`, turnLabel)}
        <pre>${tArgs}</pre>
      </div>
      <div class="turn-row agent-row">
        <div class="${bubbleClass}">
          ${roleLabel(AGENT_ICON, "Tool Response", turnLabel)}
          <pre>${tResp}</pre>
        </div>
      </div>
    </div>`;
}

/** Build the single-shot (non-multi-turn) transcript from a top-level DetailCard. */
function singleTurnTranscript(detail: DetailCard): string {
  if (detail.kind === "prompt") {
    return `<div class="turn">
      <div class="turn-row attacker-row">
        ${roleLabel(ATTACKER_ICON, "Attacker")}
        <pre>${esc(truncate(detail.prompt, 8000))}</pre>
      </div>
      <div class="turn-row agent-row">
        <div class="agent-bubble">
          ${roleLabel(AGENT_ICON, "Agent")}
          <pre>${esc(truncate(detail.response, 8000))}</pre>
        </div>
      </div>
    </div>`;
  }
  const args = esc(JSON.stringify(detail.args, null, 2));
  const resp = detail.error
    ? `Error: ${esc(truncate(detail.error, 4000))}`
    : esc(truncate(detail.response, 8000));
  const toolLabel = detail.toolName ? ` · ${esc(detail.toolName)}` : "";
  return `<div class="turn">
      <div class="turn-row attacker-row">
        ${roleLabel(ATTACKER_ICON, `Arguments${toolLabel}`)}
        <pre>${args}</pre>
      </div>
      <div class="turn-row agent-row">
        <div class="agent-bubble">
          ${roleLabel(AGENT_ICON, "Tool Response")}
          <pre>${resp}</pre>
        </div>
      </div>
    </div>`;
}

/** Render one attack result: reasoning/evidence, confidence + standards, and a collapsible transcript. */
function resultDetailCard(
  r: ResultViewModel,
  index: number,
  _mode: "agent" | "mcp",
  showTestHeading: boolean
): string {
  const verdict = r.judge.verdict;
  const failingTurns = new Set(r.judge.failingTurns ?? []);

  const hasTurns = r.turns && r.turns.length > 0;
  const turnCount = hasTurns ? r.turns!.length : 1;
  const turnsHtml = hasTurns
    ? r.turns!.map((t) => renderTurn(t, failingTurns)).join("")
    : singleTurnTranscript(r.detail);

  const tId = `t${transcriptIdCounter++}`;

  const evidenceHtml =
    r.judge.evidence && r.judge.evidence !== "N/A"
      ? `<div class="detail-section"><div class="detail-section-label">Evidence</div><div class="detail-section-body">${esc(r.judge.evidence)}</div></div>`
      : "";
  const reasoningHtml =
    verdict === "ERROR"
      ? `<div class="detail-section"><div class="detail-section-label">Error</div><div class="detail-section-body">${esc(r.judge.errorMessage ?? "")}</div></div>`
      : r.judge.reasoning
        ? `<div class="detail-section"><div class="detail-section-label">Reasoning</div><div class="detail-section-body">${esc(r.judge.reasoning)}</div></div>`
        : "";

  const confidenceCol = `
    <div class="eval-meta-col">
      <div class="detail-section-label">Confidence</div>
      <div class="meta-v-lg">${verdict === "ERROR" ? "—" : `${r.judge.confidence}%`}</div>
    </div>`;

  return `
    ${showTestHeading ? `<div class="test-heading">Test ${index + 1} — ${esc(r.label)}</div>` : ""}
    ${reasoningHtml}
    ${evidenceHtml}
    <div class="eval-meta-row">
      ${confidenceCol}
    </div>
    <div class="transcript-wrap" data-for="${tId}">
      <div class="transcript">
        <div class="transcript-header">Conversation Transcript <span class="tc-count">${turnCount} turn${turnCount === 1 ? "" : "s"}</span></div>
        ${turnsHtml}
      </div>
    </div>
    <button class="transcript-toggle" data-target="${tId}">
      <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M6 9l6 6 6-6"/></svg>
      <span class="tt-label">View more details</span>
    </button>`;
}
