#!/usr/bin/env node

// Load .env from the project the MCP server is running against.
// This lets users store GROQ_API_KEY (etc.) in their project's .env
// without having to add it to the MCP config manually.
// Search order: cwd → parent dirs (dotenv default behaviour).
import { config as loadDotenv } from "dotenv";
loadDotenv();

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import { runSetup } from "./core/setup.js";
import { runScan } from "./core/run.js";

const server = new McpServer({
  name: "astra",
  version: "0.1.0",
});

// ---------------------------------------------------------------------------
// Tool: astra_setup
// ---------------------------------------------------------------------------

server.tool(
  "astra_setup",
  "Generate red team attack prompts from a config file. " +
  "Reads the target config (JSON or YAML), selects evaluators, uses an LLM to generate " +
  "targeted attack prompts, and writes them to a prompts JSON file. " +
  "Call this before astra_run.",
  {
    config_path: z
      .string()
      .describe("Absolute or relative path to an astra config file (JSON or YAML). Example: ./myconfig.json"),
    api_key: z
      .string()
      .optional()
      .describe(
        "LLM API key for attack generation (overrides config file and env var). " +
        "If omitted, falls back to llm.apiKey in the config file, then to the provider's env var " +
        "(GROQ_API_KEY, OPENAI_API_KEY, ANTHROPIC_API_KEY, GOOGLE_GENERATIVE_AI_API_KEY)."
      ),
    output_dir: z
      .string()
      .optional()
      .default(".")
      .describe("Directory where the astra-prompts-*.json file will be written. Defaults to current directory."),
  },
  async ({ config_path, api_key, output_dir }) => {
    try {
      const result = await runSetup({
        configPath: config_path,
        apiKey: api_key,
        outputDir: output_dir,
      });

      return {
        content: [
          {
            type: "text",
            text: [
              `✅ Setup complete!`,
              ``,
              `Provider:      ${result.provider} / ${result.model}`,
              `Evaluators:    ${result.evaluatorCount}`,
              `Attack prompts: ${result.totalAttacks}`,
              `Prompts file:  ${result.promptsFilePath}`,
              ``,
              `Next step: call astra_run with input_path="${result.promptsFilePath}"`,
            ].join("\n"),
          },
        ],
      };
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      return {
        content: [{ type: "text", text: `❌ Setup failed: ${msg}` }],
        isError: true,
      };
    }
  }
);

// ---------------------------------------------------------------------------
// Tool: astra_run
// ---------------------------------------------------------------------------

server.tool(
  "astra_run",
  "Execute a red team scan using a prompts file generated by astra_setup. " +
  "Fires each attack prompt at the target endpoint, judges every response with an LLM (PASS/FAIL), " +
  "and generates HTML + JSON reports. Returns a full summary of findings.",
  {
    input_path: z
      .string()
      .describe("Path to the astra-prompts-*.json file produced by astra_setup."),
    api_key: z
      .string()
      .optional()
      .describe(
        "LLM API key for judging responses (overrides the key stored in the prompts file). " +
        "Useful when running in CI without committing keys."
      ),
    output_dir: z
      .string()
      .optional()
      .default(".astra/reports")
      .describe("Directory where HTML and JSON reports will be written. Defaults to .astra/reports."),
  },
  async ({ input_path, api_key, output_dir }) => {
    try {
      const result = await runScan({
        inputPath: input_path,
        apiKey: api_key,
        outputDir: output_dir,
      });

      const findingLines = result.criticalFindings.length > 0
        ? result.criticalFindings
            .slice(0, 5)
            .map((f, i) => `  ${i + 1}. ${f.evaluator} — Score ${f.score}/10 — ${f.description}`)
            .join("\n")
        : "  None";

      const evalLines = result.evaluatorResults
        .map(e => `  [${e.owasp}] ${e.name}: ${e.passed}✓ ${e.failed}✗ (${e.passRate}% pass)`)
        .join("\n");

      return {
        content: [
          {
            type: "text",
            text: [
              `✅ Red team scan complete!`,
              ``,
              `Target:       ${result.target}`,
              `Endpoint:     ${result.endpoint}`,
              `Tests run:    ${result.totalAttacks}`,
              `Passed:       ${result.passed}`,
              `Failed:       ${result.failed}`,
              `Safety score: ${result.safetyScore}%`,
              ``,
              `Evaluator Results:`,
              evalLines,
              ``,
              `🔴 Critical Findings${result.criticalFindings.length > 5 ? ` (top 5 of ${result.criticalFindings.length})` : ""}:`,
              findingLines,
              ``,
              `Reports:`,
              `  HTML: ${result.htmlReport}`,
              `  JSON: ${result.jsonReport}`,
            ].join("\n"),
          },
        ],
      };
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      return {
        content: [{ type: "text", text: `❌ Run failed: ${msg}` }],
        isError: true,
      };
    }
  }
);

// ---------------------------------------------------------------------------
// Start server on stdio
// ---------------------------------------------------------------------------

const transport = new StdioServerTransport();
await server.connect(transport);
